---
title: "EDA"
format: html
editor: visual
---

```{r message = FALSE}
library(dplyr)

library(knitr)

library(ggplot2)
```

## Load Datasets

```{r}
transfer <- read.csv("csv/transfer_dataset_final.csv")
transfer_1 <- transfer %>%

  filter(transfer == 1)

transfer_0 <- transfer %>%

  filter(transfer == 0)

```

------------------------------------------------------------------------

## Exploratory Data Analysis

### Completion Percentage

```{r}
sum(transfer$cmp_percent == transfer$cmp_percent_2) ## Variables are equal
```

```{r}
transfer <- transfer %>%
  mutate(avg_cmp = (cmp_percent + cmp_percent_3 + cmp_percent_4 + cmp_percent_5)/4) %>%
  transform(transfer = factor(transfer))
```

```{r}
ggplot(transfer, aes(x=transfer , y=cmp_percent)) +
geom_boxplot(aes(color = transfer), outlier.colour = NA, position = "dodge") +
geom_jitter(aes(color = transfer, x = transfer),
position = position_jitter(width = .05), alpha = 0.5) +
scale_color_manual(values = c("#2E5A35", "steelblue")) +
xlab("Transfer") +
ylab("Completion Percentage") +
ggtitle("Completion Percentage by Transfer Status") +
theme(legend.position="none")
```

### Age

```{r}
ggplot(transfer, aes(x=transfer , y=age)) +
geom_boxplot(aes(color = transfer), outlier.colour = NA, position = "dodge") +
geom_jitter(aes(color = transfer, x = transfer),
position = position_jitter(width = .05), alpha = 0.5) +
scale_color_manual(values = c("#2E5A35", "steelblue")) +
xlab("Transfer") +
ylab("Age") +
ggtitle("Age by Transfer Status") +
theme(legend.position="none")
```
